'use strict';window.DOMHandler=class{constructor(d,f){this._iRuntime=d;this._componentId=f;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(d,f,h,l){this._iRuntime.PostToRuntimeComponent(this._componentId,d,f,h,l)}PostToRuntimeAsync(d,f,h,l){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,d,f,h,l)}_PostToRuntimeMaybeSync(d,f,h){this._iRuntime.UsesWorker()?this.PostToRuntime(d,f,h):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:d,dispatchOpts:h||null,data:f,responseId:null})}AddRuntimeMessageHandler(d,f){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,d,f)}AddRuntimeMessageHandlers(d){for(const [f,h]of d)this.AddRuntimeMessageHandler(f,h)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(d,f){this._callback=d;this._interval=f;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(d){this._canRunImmediate=!!d}Call(){if(-1===this._timerId){var d=Date.now(),f=d-this._lastCallTime,h=this._interval;f>=h&&this._canRunImmediate?(this._lastCallTime=d,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(h-f,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(d,f){super(d,f);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",h=>this._OnCreate(h)],["destroy",h=>this._OnDestroy(h)],["set-visible",h=>this._OnSetVisible(h)],["update-position",h=>this._OnUpdatePosition(h)],["update-state",h=>this._OnUpdateState(h)],["focus",h=>this._OnSetFocus(h)],["set-css-style",h=>this._OnSetCssStyle(h)],["set-attribute",h=>this._OnSetAttribute(h)],["remove-attribute",
h=>this._OnRemoveAttribute(h)]]);this.AddDOMElementMessageHandler("get-element",h=>h)}SetAutoAttach(d){this._autoAttach=!!d}AddDOMElementMessageHandler(d,f){this.AddRuntimeMessageHandler(d,h=>{const l=this._elementMap.get(h.elementId);return f(l,h)})}_OnCreate(d){const f=d.elementId,h=this.CreateElement(f,d);this._elementMap.set(f,h);d.isVisible||(h.style.display="none");d=this._GetFocusElement(h);d.addEventListener("focus",l=>this._OnFocus(f));d.addEventListener("blur",l=>this._OnBlur(f));this._autoAttach&&
document.body.appendChild(h)}CreateElement(d,f){throw Error("required override");}DestroyElement(d){}_OnDestroy(d){d=d.elementId;const f=this._elementMap.get(d);this.DestroyElement(f);this._autoAttach&&f.parentElement.removeChild(f);this._elementMap.delete(d)}PostToRuntimeElement(d,f,h){h||(h={});h.elementId=f;this.PostToRuntime(d,h)}_PostToRuntimeElementMaybeSync(d,f,h){h||(h={});h.elementId=f;this._PostToRuntimeMaybeSync(d,h)}_OnSetVisible(d){this._autoAttach&&(this._elementMap.get(d.elementId).style.display=
d.isVisible?"":"none")}_OnUpdatePosition(d){if(this._autoAttach){var f=this._elementMap.get(d.elementId);f.style.left=d.left+"px";f.style.top=d.top+"px";f.style.width=d.width+"px";f.style.height=d.height+"px";d=d.fontSize;null!==d&&(f.style.fontSize=d+"em")}}_OnUpdateState(d){const f=this._elementMap.get(d.elementId);this.UpdateState(f,d)}UpdateState(d,f){throw Error("required override");}_GetFocusElement(d){return d}_OnFocus(d){this.PostToRuntimeElement("elem-focused",d)}_OnBlur(d){this.PostToRuntimeElement("elem-blurred",
d)}_OnSetFocus(d){const f=this._GetFocusElement(this._elementMap.get(d.elementId));d.focus?f.focus():f.blur()}_OnSetCssStyle(d){this._elementMap.get(d.elementId).style[d.prop]=d.val}_OnSetAttribute(d){this._elementMap.get(d.elementId).setAttribute(d.name,d.val)}_OnRemoveAttribute(d){this._elementMap.get(d.elementId).removeAttribute(d.name)}GetElementById(d){return this._elementMap.get(d)}};"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function f(b,a){const c=document.createElement("script");c.async=!1;"module"===a&&(c.type="module");if(b.isStringSrc)c.textContent=b.str,document.head.appendChild(c);else return new Promise((e,g)=>{c.onload=e;c.onerror=g;c.src=b;document.head.appendChild(c)})}let h=!1,l=!1;function z(){if(!h){try{new Worker("blob://",{get type(){l=!0}})}catch(b){}h=!0}return l}let r=new Audio;const A={"audio/webm; codecs=opus":!!r.canPlayType("audio/webm; codecs=opus"),
"audio/ogg; codecs=opus":!!r.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!r.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!r.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!r.canPlayType("audio/mp4"),"audio/mpeg":!!r.canPlayType("audio/mpeg")};r=null;async function D(b){b=await t(b);return(new TextDecoder("utf-8")).decode(b)}function t(b){return new Promise((a,c)=>{const e=new FileReader;e.onload=g=>a(g.target.result);e.onerror=g=>c(g);e.readAsArrayBuffer(b)})}
const x=[];let v=0;window.RealFile=window.File;const u=[],y=new Map,p=new Map;let B=0;const w=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");w.push(b)};const E=new Set(["cordova","playable-ad","instant-games"]);function C(b){return E.has(b)}window.RuntimeInterface=class b{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._scriptsType=a.scriptsType;this._workerScriptURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this._scriptsType||z())||(this._useWorker=!1);C(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",c=>this._OnCordovaFetchLocalFile(c));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",
c=>this._OnCreateJobWorker(c));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return d&&
"cordova"===this._exportType}IsiOSWebView(){return d&&C(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let e=0,g=a.engineScripts.length;e<g;++e){var c=a.engineScripts[e].toLowerCase();this._localFileStrings.hasOwnProperty(c)?a.engineScripts[e]={isStringSrc:!0,str:this._localFileStrings[c]}:this._localFileBlobs.hasOwnProperty(c)&&(a.engineScripts[e]=
URL.createObjectURL(this._localFileBlobs[c]))}}a.baseUrl?this._baseUrl=a.baseUrl:(c=location.origin,this._baseUrl=("null"===c?"file:///":c)+location.pathname,c=this._baseUrl.lastIndexOf("/"),-1!==c&&(this._baseUrl=this._baseUrl.substr(0,c+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);c=new MessageChannel;this._messageChannelPort=c.port1;this._messageChannelPort.onmessage=e=>this._OnMessageFromRuntime(e.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(e=>this._OnMessageFromDebugger(e));
this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,c.port2):await this._InitDOM(a,c.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,c,e){if(a.startsWith("blob:"))return new Worker(a,e);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),
e);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),e)}return new Worker(a,e)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}MaybeForceBodySize(){if(this.IsiOSWebView()){const a=document.documentElement.style,c=document.body.style,e=window.innerWidth<window.innerHeight,g=e?window.screen.width:window.screen.height;
c.height=a.height=(e?window.screen.height:window.screen.width)+"px";c.width=a.width=g+"px"}}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:b.IsDocumentFullscreen(),projectData:a.projectData,scriptsType:a.scriptsType,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileUrls:window.cr_previewProjectFiles,
swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:A,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,
c){var e=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(e,this._baseUrl,{type:this._scriptsType,name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";e=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:a.workerDependencyScripts||
[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=u.map(g=>new g(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(g,k)=>this._runtimeDomHandler._InvokeFunctionFromJS(g,k);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,c){this._canvas=
document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=u.map(k=>new k(this));this._FindRuntimeDOMHandler();var e=a.engineScripts.map(k=>"string"===typeof k?(new URL(k,this._baseUrl)).toString():k);Array.isArray(a.workerDependencyScripts)&&e.unshift(...a.workerDependencyScripts);e=await Promise.all(e.map(k=>this._MaybeGetCordovaScriptURL(k,this._scriptsType)));await Promise.all(e.map(k=>f(k,this._scriptsType)));
const g=self.C3_ProjectScriptsStatus;if("module"===this._scriptsType){e=a.mainProjectScript;const k=a.projectScripts;for(let [n,m]of k)if(m||(m=n),n===e)try{m=await this._MaybeGetCordovaScriptURL(m,this._scriptsType),await f(m,this._scriptsType),"preview"!==this._exportType||g[n]||this._ReportProjectMainScriptError(n,"main script did not run to completion")}catch(q){this._ReportProjectMainScriptError(n,q)}else if("scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m=await this._MaybeGetCordovaScriptURL(m,
this._scriptsType),await f(m,this._scriptsType)}else if(a.projectScripts&&0<a.projectScripts.length)try{if(await Promise.all(a.projectScripts.map(k=>f(k[1],this._scriptsType))),Object.values(g).some(k=>!k)){self.setTimeout(()=>this._ReportProjectScriptError(g),100);return}}catch(k){console.error("[Preview] Error loading project scripts: ",k);self.setTimeout(()=>this._ReportProjectScriptError(g),100);return}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),
console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:c,canvas:this._canvas,runOnStartupFunctions:w}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){this._RemoveLoadingMessage();
a=`Failed to load project script '${Object.entries(a).filter(c=>!c[1]).map(c=>c[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}_ReportProjectMainScriptError(a,c){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,c,e,g,k){this._messageChannelPort.postMessage({type:"event",component:a,handler:c,dispatchOpts:g||null,data:e,responseId:null},k)}PostToRuntimeComponentAsync(a,
c,e,g,k){const n=B++,m=new Promise((q,F)=>{p.set(n,{resolve:q,reject:F})});this._messageChannelPort.postMessage({type:"event",component:a,handler:c,dispatchOpts:g||null,data:e,responseId:n},k);return m}["_OnMessageFromRuntime"](a){const c=a.type;if("event"===c)return this._OnEventFromRuntime(a);if("result"===c)this._OnResultFromRuntime(a);else if("runtime-ready"===c)this._OnRuntimeReady();else if("alert-error"===c)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===c)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${c}'`);}_OnEventFromRuntime(a){const c=a.component,e=a.handler,g=a.data,k=a.responseId;if(a=y.get(c))if(a=a.get(e)){var n=null;try{n=a(g)}catch(m){console.error(`Exception in '${c}' handler '${e}':`,m);null!==k&&this._PostResultToRuntime(k,!1,""+m);return}if(null===k)return n;n&&n.then?n.then(m=>this._PostResultToRuntime(k,!0,m)).catch(m=>{console.error(`Rejection from '${c}' handler '${e}':`,m);this._PostResultToRuntime(k,!1,""+m)}):this._PostResultToRuntime(k,
!0,n)}else console.warn(`[DOM] No handler '${e}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}_PostResultToRuntime(a,c,e){let g;e&&e.transferables&&(g=e.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:c,result:e},g)}_OnResultFromRuntime(a){const c=a.responseId,e=a.isOk;a=a.result;const g=p.get(c);e?g.resolve(a):g.reject(a);p.delete(c)}AddRuntimeComponentMessageHandler(a,c,e){let g=y.get(a);g||(g=new Map,y.set(a,g));if(g.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
g.set(c,e)}static AddDOMHandlerClass(a){if(u.includes(a))throw Error("DOM handler already added");u.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==
this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!A[a]}async _WasmDecodeWebMOpus(a){a=await this.PostToRuntimeComponentAsync("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a,c){return"cordova"===this._exportType&&"module"===c&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),a=new Blob([a],
{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const c=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(c);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(c);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,c){a=
a[c];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const c=this._GetPermissionAPI();return new Promise((e,g)=>c.checkPermission(this._MapPermissionID(c,a),k=>e(!!k.hasPermission),g))}_RequestPermission(a){const c=this._GetPermissionAPI();return new Promise((e,g)=>c.requestPermission(this._MapPermissionID(c,a),k=>e(!!k.hasPermission),g))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const c of a)if(!await this._HasPermission(c)&&
!1===await this._RequestPermission(c))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((e,g)=>{window.resolveLocalFileSystemURL(c,k=>{k.file(e,g)},g)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await D(a)}_CordovaMaybeStartNextArrayBufferRead(){if(x.length&&!(8<=v)){v++;
var a=x.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((c,e)=>{x.push({filename:a,successCallback:g=>{v--;this._CordovaMaybeStartNextArrayBufferRead();c(g)},errorCallback:g=>{v--;this._CordovaMaybeStartNextArrayBufferRead();e(g)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,c,e){try{const g=await this.CordovaFetchLocalFile(a),k=await t(g);
c(k)}catch(g){e(g)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [c,e]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(c,e));await Promise.all(a)}async _ConvertDataUriToBlobs(a,c){if("object"===typeof c)this._localFileBlobs[a]=new Blob([c.str],{type:c.type}),this._localFileStrings[a]=c.str;else{let e=await this._FetchDataUri(c);e||(e=this._DataURIToBinaryBlobSync(c));this._localFileBlobs[a]=e}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var e=a.substring(5,c);a=a.substring(c+1);c=e.split(";");e=c[0]||"";const g=c[2];a="base64"===c[1]||"base64"===g?atob(a):decodeURIComponent(a);return{mime_type:e,data:a}}_BinaryStringToBlob(a,c){var e=a.length;let g=e>>2,k=new Uint8Array(e),n=new Uint32Array(k.buffer,0,g),m,q;for(q=m=0;m<g;++m)n[m]=
a.charCodeAt(q++)|a.charCodeAt(q++)<<8|a.charCodeAt(q++)<<16|a.charCodeAt(q++)<<24;for(e&=3;e--;)k[q]=a.charCodeAt(q),++q;return new Blob([k],{type:c})}}}"use strict";
{const d=self.RuntimeInterface;function f(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const h=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),l={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},z={dispatchUserScriptEvent:!0},r={dispatchRuntimeEvent:!0};function A(b){return new Promise((a,c)=>{const e=document.createElement("link");e.onload=()=>a(e);e.onerror=
g=>c(g);e.rel="stylesheet";e.href=b;document.head.appendChild(e)})}function D(b){return new Promise((a,c)=>{const e=new Image;e.onload=()=>a(e);e.onerror=g=>c(g);e.src=b})}async function t(b){b=URL.createObjectURL(b);try{return await D(b)}finally{URL.revokeObjectURL(b)}}function x(b){return new Promise((a,c)=>{let e=new FileReader;e.onload=g=>a(g.target.result);e.onerror=g=>c(g);e.readAsText(b)})}async function v(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await t(b);var e=await x(b);e=
(new DOMParser).parseFromString(e,"image/svg+xml");const g=e.documentElement;if(g.hasAttribute("width")&&g.hasAttribute("height")){const k=g.getAttribute("width"),n=g.getAttribute("height");if(!k.includes("%")&&!n.includes("%"))return await t(b)}g.setAttribute("width",a+"px");g.setAttribute("height",c+"px");e=(new XMLSerializer).serializeToString(e);b=new Blob([e],{type:"image/svg+xml"});return await t(b)}function u(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const y=new Set(["canvas","body","html"]);function p(b){const a=b.target.tagName.toLowerCase();y.has(a)&&b.preventDefault()}function B(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await t(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]}};
self.C3_RasterSvgImageBlob=async function(b,a,c,e,g){b=await v(b,a,c);const k=document.createElement("canvas");k.width=e;k.height=g;k.getContext("2d").drawImage(b,0,0,a,c);return k};let w=!1;document.addEventListener("pause",()=>w=!0);document.addEventListener("resume",()=>w=!1);function E(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function C(){const b=document.activeElement;if(!b)return!1;const a=b.tagName.toLowerCase(),c=new Set("email number password search tel text url".split(" "));
return"textarea"===a?!0:"input"===a?c.has(b.type.toLowerCase()||"text"):u(b)}d.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",e=>this._OnUpdateCanvasSize(e));
b.AddRuntimeComponentMessageHandler("runtime","invoke-download",e=>this._OnInvokeDownload(e));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",e=>this._OnRasterSvgImage(e));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",e=>this._OnGetSvgImageSize(e));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",e=>this._OnSetTargetOrientation(e));b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime",
"post-to-debugger",e=>this._OnPostToDebugger(e));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",e=>this._OnPostToDebugger(e));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",e=>this._OnDebugHighlight(e));b.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",
()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",e=>this._OnAddStylesheet(e));b.AddRuntimeComponentMessageHandler("runtime","alert",e=>this._OnAlert(e));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const g=e.target,k=g.tagName.toLowerCase();a.has(k)||u(g)||e.preventDefault()});const c=b.GetCanvas();window.addEventListener("selectstart",
p);window.addEventListener("gesturehold",p);c.addEventListener("selectstart",p);c.addEventListener("gesturehold",p);window.addEventListener("touchstart",p,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",p,{passive:!1}),c.addEventListener("pointerdown",p)):c.addEventListener("touchstart",p);this._mousePointerLastButtons=0;window.addEventListener("mousedown",e=>{1===e.button&&e.preventDefault()});window.addEventListener("mousewheel",B,{passive:!1});window.addEventListener("wheel",
B,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());b.IsiOSWebView()&&window.addEventListener("focusout",()=>{C()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",
()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!w)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:E()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",
()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("webkitfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("mozfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,l));window.addEventListener("wheel",a=>
this._OnMouseWheelEvent("wheel",a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):
window.addEventListener("pointermove",a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",
a)),window.addEventListener("touchstart",a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);
window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,a){this.PostToRuntime(b,a||null,r)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&
(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,a,0))}_ScheduleSimulatedResize(b,a,c){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(b,a,c),48)}_OnSimulatedResize(b,a,c){const e=this._GetWindowInnerWidth(),g=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;e!=b||g!=a?this._PostRuntimeEvent("window-resize",{innerWidth:e,innerHeight:g,
devicePixelRatio:window.devicePixelRatio}):10>c&&this._ScheduleSimulatedResize(e,g,c+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?
a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}_OnFullscreenChange(){const b=d.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",
b);this.PostToRuntime("fullscreenerror",{isFullscreen:d.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,a){"Backspace"===a.key&&p(a);const c=h.get(a.code)||a.code;this._PostToRuntimeMaybeSync(b,{code:c,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,
metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},l)}_OnMouseWheelEvent(b,a){this.PostToRuntime(b,{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},l)}_OnMouseEvent(b,a,c){f(a)||this._PostToRuntimeMaybeSync(b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},c)}_OnMouseEventAsPointer(b,a){if(!f(a)){var c=this._mousePointerLastButtons;
"pointerdown"===b&&0!==c?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},l);this._mousePointerLastButtons=a.buttons;this._OnMouseEvent(a.type,a,z)}}_OnPointerEvent(b,a){this._pointerRawUpdateRateLimiter&&"pointermove"!==
b&&this._pointerRawUpdateRateLimiter.Reset();var c=0;"mouse"===a.pointerType&&(c=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},l);"mouse"===a.pointerType&&
(c="mousemove","pointerdown"===b?c="mousedown":"pointerup"===b&&(c="mouseup"),this._OnMouseEvent(c,a,z),this._mousePointerLastButtons=a.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,a){for(let c=0,e=a.changedTouches.length;c<e;++c){const g=a.changedTouches[c];this._PostToRuntimeMaybeSync(b,{pointerId:g.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:2*(g.radiusX||g.webkitRadiusX||0),height:2*(g.radiusY||g.webkitRadiusY||0),pressure:g.force||g.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:g.rotationAngle||0,timeStamp:a.timeStamp},l)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=
!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},l)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},l)}_OnDeviceMotion(b){let a=
null;var c=b.acceleration;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=b.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;const g=b.rotationRate;g&&(e={alpha:g.alpha||0,beta:g.beta||0,gamma:g.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:c,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},l)}_OnUpdateCanvasSize(b){const a=this.GetRuntimeInterface(),c=a.GetCanvas();c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+
"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";a.MaybeForceBodySize();this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const a=b.url;b=b.filename;const c=document.createElement("a"),e=document.body;c.textContent=b;c.href=a;c.download=b;e.appendChild(c);c.click();e.removeChild(c)}async _OnRasterSvgImage(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);
a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await A(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of b)(b=a.play())&&b.catch(c=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");
this._mediaRemovedPendingPlay.delete(b);let a;try{a=b.play()}catch(c){this._mediaPendingPlay.add(b);return}a&&a.catch(c=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,a){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:a})}_OnAlert(b){alert(b.message)}})}"use strict";
self.JobSchedulerDOM=class{constructor(d){this._runtimeInterface=d;this._baseUrl=d.GetBaseURL();"preview"===d.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=d.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var d=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(d,this._baseUrl,{name:"DispatchWorker"});d=new MessageChannel;this._inputPort=d.port1;this._dispatchWorker.postMessage({type:"_init","in-port":d.port2},[d.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const d=this._jobWorkers.length;var f=this._runtimeInterface._GetWorkerURL("jobworker.js");f=await this._runtimeInterface.CreateWorker(f,this._baseUrl,{name:"JobWorker"+d});const h=new MessageChannel,l=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:h.port1},[h.port1]);f.postMessage({type:"init",number:d,"dispatch-port":h.port2,"output-port":l.port2},[h.port2,l.port2]);this._jobWorkers.push(f);return l.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!1,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptsType:"module",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",f=>this._OnGetInitialState(f)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",f=>this._OnAlert(f)],["close",()=>this._OnClose()],["set-focus",f=>this._OnSetFocus(f)],["vibrate",f=>this._OnVibrate(f)],["lock-orientation",f=>this._OnLockOrientation(f)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",f=>this._OnNavigate(f)],["request-fullscreen",f=>this._OnRequestFullscreen(f)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",f=>this._OnSetHash(f)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
f=>this._OnWin10BackRequested(f))}_OnGetInitialState(d){this._exportType=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>
this.PostToRuntime("sw-message",d.data))}_OnOnlineStateChanged(d){this.PostToRuntime("online-state",{isOnline:d})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(d){d.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(d){alert(d.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(d){d=
d.isFocus;if("nwjs"===this._exportType){const f=this.GetNWjsWindow();d?f.focus():f.blur()}else d?window.focus():window.blur()}_OnVibrate(d){navigator.vibrate&&navigator.vibrate(d.pattern)}_OnLockOrientation(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(d):screen.webkitLockOrientation?f=screen.webkitLockOrientation(d):
screen.mozLockOrientation?f=screen.mozLockOrientation(d):screen.msLockOrientation&&(f=screen.msLockOrientation(d));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}_OnNavigate(d){var f=d.type;if("back"===f)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===f)window.forward();else if("home"===f)window.home();else if("reload"===f)location.reload();else if("url"===f){f=d.url;var h=d.target;d=d.exportType;"windows-uwp"===d&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(f,"_system"):"preview"===d?window.open(f,"_blank"):this._isScirraArcade||(2===h?window.top.location=f:1===h?window.parent.location=f:window.location=f)}else"new-window"===f&&(f=d.url,h=d.tag,"windows-uwp"===d.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):window.open(f,h))}_OnRequestFullscreen(d){const f={navigationUI:"auto"};
d=d.navUI;1===d?f.navigationUI="hide":2===d&&(f.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(f):d.mozRequestFullScreen?d.mozRequestFullScreen(f):d.msRequestFullscreen?d.msRequestFullscreen(f):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}_OnExitFullscreen(){document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():
document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}_OnSetHash(d){location.hash=d.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"mouse");this.AddRuntimeMessageHandler("cursor",f=>this._OnChangeCursorStyle(f))}_OnChangeCursorStyle(d){document.documentElement.style.cursor=d}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(d){super(d,"touch");this.AddRuntimeMessageHandler("request-permission",f=>this._OnRequestPermission(f))}async _OnRequestPermission(d){d=d.type;let f=!0;0===d?f=await this._RequestOrientationPermission():1===d&&(f=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:d,result:f})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}});
